<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <UseWPF>true</UseWPF>
        <TargetFrameworks>net48;net10.0-windows</TargetFrameworks>
        <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
        <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    </PropertyGroup>

    <PropertyGroup>
        <Title>$(AssemblyName)</Title>
        <Version>1.1.0</Version>
        <Authors>qian-o</Authors>
        <Copyright>MIT</Copyright>
        <PackageTags>AvalonDock;WPFUI</PackageTags>
        <Description>Use WPF-UI to make AvalonDock themes.</Description>
        <RepositoryUrl>https://github.com/qian-o/AvalonDock.Themes.WPFUI</RepositoryUrl>
        <PackageProjectUrl>https://github.com/qian-o/AvalonDock.Themes.WPFUI</PackageProjectUrl>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Dirkster.AvalonDock" Version="5.0.0" />
        <PackageReference Include="WPF-UI" Version="4.3.0" />
    </ItemGroup>

    <ItemGroup>
        <None Include="..\..\LICENSE">
            <Pack>True</Pack>
            <PackagePath>\</PackagePath>
        </None>
    </ItemGroup>

    <ItemGroup>
        <None Include="..\..\README.md">
            <Pack>True</Pack>
            <PackagePath>\</PackagePath>
        </None>
    </ItemGroup>

</Project>
